### ISSUE TITLE
npm run test command failed - .\bin\test.sh not found! Please help!

### ISSUE THREAD

**Issue by shalu0628** [hackingbeauty/react-dapp-boilerplate-with-drizzle#9]
I have followed the instructions and facing the below issues. Any help is appreciated!
npm run test

> ReactDappBoilerplate@2.0.0 test /home/myfolder/myreactDapp
> bin/test.sh

sh: 1: bin/test.sh: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ReactDappBoilerplate@2.0.0 test: `bin/test.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ReactDappBoilerplate@2.0.0 test script.

> What kind of tests are you trying to execute?

> What kind of tests are you trying to execute?

I am so sorry, I didnt compile my contracts! I am newbie here.. Please close the issue!

**Comment by hackingbeauty** [comment]
What kind of tests are you trying to execute?

**Comment by shalu0628** [comment]
@hackingbeauty - Thank you very much for your quick response! I am a newbie here.. So, I  just followed the instructions in the readme. Am I missing something here?

**Comment by hackingbeauty** [comment]
This is now fixed.
